language: node_js
node_js:
  - "8.11"

branches:
  only:
    - develop

before_install:
  - openssl aes-256-cbc -K $encrypted_fc47f491639d_key -iv $encrypted_fc47f491639d_iv -in github_deploy_key.enc -out github_deploy_key -d

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
  - node_modules

script:
  - ng lint
  - ng build --prod
  - yarn docs
  - yarn docs:copy

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  target-branch: master
  on:
    branch: develop
